name: Deploy to EC2 for Application Server 02

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to EC2 for Application Server 02
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            cd ~/apps/Deploying_Multiple_Node_App_002 &&
            git pull origin main &&
            npm install && npm run build &&
            pm2 stop Node_App_002 || pm2 delete Node_App_002;  pm2 start npm --name "Node_App_002" -- start && pm2 save
          '
